blank_issues_enabled: false
contact_links:
  - name: RFCXML language or template issues
    url: https://github.com/ietf-tools/RFCXML/issues/new
    about: Propose changes to the RFCXML language or raise an issue with one of the RFCXML templates.
